ARG BUILD_FROM=intel/oneapi:2025.0.1-0-devel-ubuntu24.04
FROM ${BUILD_FROM}

ARG WHISPER_CPP_VERSION=1.7.4

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        netcat-traditional \
        intel-opencl-icd \
        clinfo

RUN \
    git clone https://github.com/ggerganov/whisper.cpp.git whisper.cpp \
    && cd whisper.cpp \
    && git reset --hard v${WHISPER_CPP_VERSION} \
    && cmake -B build -DGGML_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_SYCL_F16=ON \
    && cmake --build build -j --config Release

WORKDIR /whisper.cpp
